name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8
      - run: golangci-lint run ./...

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: go mod tidy
      - run: go test ./... -v -coverprofile=coverage-unit.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage-unit.out
          flags: unit
          name: CI
          token: ${{ secrets.CODECOV_TOKEN }}

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: go mod tidy
      - run: go test ./... -v -tags=integration -coverprofile=coverage-integration.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage-integration.out
          flags: integration
          name: CI
          token: ${{ secrets.CODECOV_TOKEN }}
